blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/yourusername/mailarchive/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/yourusername/mailarchive/security/advisories/new
    about: Report security vulnerabilities privately
  - name: Documentation
    url: https://docs.mailarchive.example.com
    about: Check the documentation for help
