blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/philharmonie/mailarchive/security/advisories/new
    about: Report security vulnerabilities privately
